// <auto-generated />
using System;
using BF2Statistics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BF2Statistics.Migrations
{
    [DbContext(typeof(BF2StatisticsContext))]
    [Migration("20251001080536_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BF2Statistics.Models.Army", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ammos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammos");

                    b.Property<int>("Best0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best0");

                    b.Property<int>("Best1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best1");

                    b.Property<int>("Best2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best2");

                    b.Property<int>("Best3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best3");

                    b.Property<int>("Best4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best4");

                    b.Property<int>("Best5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best5");

                    b.Property<int>("Best6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best6");

                    b.Property<int>("Best7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best7");

                    b.Property<int>("Best8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best8");

                    b.Property<int>("BestScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("bestscore");

                    b.Property<int>("Bested")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bested");

                    b.Property<int>("Brnd0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd0");

                    b.Property<int>("Brnd1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd1");

                    b.Property<int>("Brnd2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd2");

                    b.Property<int>("Brnd3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd3");

                    b.Property<int>("Brnd4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd4");

                    b.Property<int>("Brnd5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd5");

                    b.Property<int>("Brnd6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd6");

                    b.Property<int>("Brnd7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd7");

                    b.Property<int>("Brnd8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("brnd8");

                    b.Property<int>("CaptureAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captureassists");

                    b.Property<int>("Captures")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captures");

                    b.Property<int>("CmdTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cmdtime");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("damageassists");

                    b.Property<int>("DeathStreak")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deathstreak");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths");

                    b.Property<int>("Defends")
                        .HasColumnType("INTEGER")
                        .HasColumnName("defends");

                    b.Property<int>("DriverAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driverassists");

                    b.Property<int>("DriverSpecials")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driverspecials");

                    b.Property<int>("Heals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heals");

                    b.Property<int>("KillStreak")
                        .HasColumnType("INTEGER")
                        .HasColumnName("killstreak");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills");

                    b.Property<int>("Loss0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss0");

                    b.Property<int>("Loss1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss1");

                    b.Property<int>("Loss2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss2");

                    b.Property<int>("Loss3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss3");

                    b.Property<int>("Loss4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss4");

                    b.Property<int>("Loss5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss5");

                    b.Property<int>("Loss6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss6");

                    b.Property<int>("Loss7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss7");

                    b.Property<int>("Loss8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loss8");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("losses");

                    b.Property<int>("LwTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lwtime");

                    b.Property<int>("NeutralizeAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("neutralizeassists");

                    b.Property<int>("Neutralizes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("neutralizes");

                    b.Property<int>("PassengerAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passengerassists");

                    b.Property<int>("Repairs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repairs");

                    b.Property<int>("Revives")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revives");

                    b.Property<int>("RndScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rndscore");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("score");

                    b.Property<int>("Score0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score0");

                    b.Property<int>("Score1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score1");

                    b.Property<int>("Score2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score2");

                    b.Property<int>("Score3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score3");

                    b.Property<int>("Score4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score4");

                    b.Property<int>("Score5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score5");

                    b.Property<int>("Score6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score6");

                    b.Property<int>("Score7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score7");

                    b.Property<int>("Score8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score8");

                    b.Property<int>("SqlTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sqltime");

                    b.Property<int>("SqmTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sqmtime");

                    b.Property<int>("Suicides")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suicides");

                    b.Property<int>("TargetAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("targetassists");

                    b.Property<int>("TeamDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamdamage");

                    b.Property<int>("TeamKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamkills");

                    b.Property<int>("TeamVehicleDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamvehicledamage");

                    b.Property<int>("Time0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time0");

                    b.Property<int>("Time1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time1");

                    b.Property<int>("Time2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time2");

                    b.Property<int>("Time3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time3");

                    b.Property<int>("Time4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time4");

                    b.Property<int>("Time5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time5");

                    b.Property<int>("Time6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time6");

                    b.Property<int>("Time7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time7");

                    b.Property<int>("Time8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time8");

                    b.Property<int>("Win0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win0");

                    b.Property<int>("Win1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win1");

                    b.Property<int>("Win2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win2");

                    b.Property<int>("Win3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win3");

                    b.Property<int>("Win4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win4");

                    b.Property<int>("Win5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win5");

                    b.Property<int>("Win6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win6");

                    b.Property<int>("Win7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win7");

                    b.Property<int>("Win8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("win8");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.Property<int>("Worst0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst0");

                    b.Property<int>("Worst1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst1");

                    b.Property<int>("Worst2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst2");

                    b.Property<int>("Worst3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst3");

                    b.Property<int>("Worst4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst4");

                    b.Property<int>("Worst5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst5");

                    b.Property<int>("Worst6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst6");

                    b.Property<int>("Worst7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst7");

                    b.Property<int>("Worst8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst8");

                    b.Property<int>("WorstScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("worstscore");

                    b.Property<int>("Worsted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worsted");

                    b.HasKey("Id");

                    b.ToTable("army");
                });

            modelBuilder.Entity("BF2Statistics.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AwardId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("awardid");

                    b.Property<int>("Earned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("earned");

                    b.Property<byte>("First")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("first");

                    b.Property<byte>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("level");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("When")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("when");

                    b.HasKey("Id");

                    b.ToTable("awards");
                });

            modelBuilder.Entity("BF2Statistics.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 10, 1, 8, 5, 36, 594, DateTimeKind.Utc).AddTicks(2928))
                        .HasColumnName("created_at");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_mode");

                    b.Property<int>("GamePort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("game_port");

                    b.Property<double>("MapEnd")
                        .HasColumnType("REAL")
                        .HasColumnName("map_end");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("map_id");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("map_name");

                    b.Property<double>("MapStart")
                        .HasColumnType("REAL")
                        .HasColumnName("map_start");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mod_id");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pc");

                    b.Property<int>("QueryPort")
                        .HasColumnType("INTEGER")
                        .HasColumnName("query_port");

                    b.Property<int>("RoundsArmy1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ra1");

                    b.Property<int>("RoundsArmy2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ra2");

                    b.Property<int>("ScoreArmy1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rs1");

                    b.Property<int>("ScoreArmy2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rs2");

                    b.Property<int>("ScoreTeam2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rst2");

                    b.Property<string>("ServerIp")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("server_ip");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(2025, 10, 1, 8, 5, 36, 594, DateTimeKind.Utc).AddTicks(3180))
                        .HasColumnName("updated_at");

                    b.Property<string>("Version")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("bf2")
                        .HasColumnName("version");

                    b.Property<int>("Winner")
                        .HasColumnType("INTEGER")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MapName");

                    b.HasIndex("MapStart");

                    b.HasIndex("ServerIp");

                    b.ToTable("game_sessions");
                });

            modelBuilder.Entity("BF2Statistics.Models.Ip2Nation", b =>
                {
                    b.Property<int>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ip");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country");

                    b.HasKey("Ip");

                    b.ToTable("ip2nation");
                });

            modelBuilder.Entity("BF2Statistics.Models.Kill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Attacker")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attacker");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER")
                        .HasColumnName("count");

                    b.Property<int>("Victim")
                        .HasColumnType("INTEGER")
                        .HasColumnName("victim");

                    b.HasKey("Id");

                    b.ToTable("kills");
                });

            modelBuilder.Entity("BF2Statistics.Models.Kit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Deaths0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths0");

                    b.Property<int>("Deaths1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths1");

                    b.Property<int>("Deaths2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths2");

                    b.Property<int>("Deaths3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths3");

                    b.Property<int>("Deaths4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths4");

                    b.Property<int>("Deaths5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths5");

                    b.Property<int>("Deaths6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths6");

                    b.Property<int>("Kills0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills0");

                    b.Property<int>("Kills1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills1");

                    b.Property<int>("Kills2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills2");

                    b.Property<int>("Kills3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills3");

                    b.Property<int>("Kills4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills4");

                    b.Property<int>("Kills5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills5");

                    b.Property<int>("Kills6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills6");

                    b.Property<int>("Time0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time0");

                    b.Property<int>("Time1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time1");

                    b.Property<int>("Time2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time2");

                    b.Property<int>("Time3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time3");

                    b.Property<int>("Time4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time4");

                    b.Property<int>("Time5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time5");

                    b.Property<int>("Time6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time6");

                    b.HasKey("Id");

                    b.ToTable("kits");
                });

            modelBuilder.Entity("BF2Statistics.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mapid");

                    b.Property<int>("Best")
                        .HasColumnType("INTEGER")
                        .HasColumnName("best");

                    b.Property<int>("Loss")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("loss");

                    b.Property<int>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time");

                    b.Property<int>("Win")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("win");

                    b.Property<int>("Worst")
                        .HasColumnType("INTEGER")
                        .HasColumnName("worst");

                    b.HasKey("Id", "MapId");

                    b.ToTable("maps");
                });

            modelBuilder.Entity("BF2Statistics.Models.MapInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assists");

                    b.Property<int>("Captures")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captures");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rounds");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.Property<int>("Times")
                        .HasColumnType("INTEGER")
                        .HasColumnName("times");

                    b.HasKey("Id");

                    b.ToTable("mapinfo");
                });

            modelBuilder.Entity("BF2Statistics.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ammos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ammos");

                    b.Property<byte>("AvailableUnlocks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availunlocks");

                    b.Property<int>("Banned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("banned");

                    b.Property<int>("CaptureAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captureassists");

                    b.Property<int>("Captures")
                        .HasColumnType("INTEGER")
                        .HasColumnName("captures");

                    b.Property<byte>("Chng")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chng");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("clantag");

                    b.Property<int>("CmdScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cmdscore");

                    b.Property<int>("CmdTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cmdtime");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("xx")
                        .HasColumnName("country");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("damageassists");

                    b.Property<int>("DeathStreak")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deathstreak");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths");

                    b.Property<byte>("Decr")
                        .HasColumnType("INTEGER")
                        .HasColumnName("decr");

                    b.Property<int>("Defends")
                        .HasColumnType("INTEGER")
                        .HasColumnName("defends");

                    b.Property<int>("DriverAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driverassists");

                    b.Property<int>("DriverSpecials")
                        .HasColumnType("INTEGER")
                        .HasColumnName("driverspecials");

                    b.Property<int>("Heals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heals");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("ip");

                    b.Property<int>("Joined")
                        .HasColumnType("INTEGER")
                        .HasColumnName("joined");

                    b.Property<int>("Kicked")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kicked");

                    b.Property<int>("KillStreak")
                        .HasColumnType("INTEGER")
                        .HasColumnName("killstreak");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills");

                    b.Property<int>("LastOnline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lastonline");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER")
                        .HasColumnName("losses");

                    b.Property<int>("LwTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lwtime");

                    b.Property<int>("Mode0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode0");

                    b.Property<int>("Mode1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode1");

                    b.Property<int>("Mode2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("name");

                    b.Property<int>("NeutralizeAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("neutralizeassists");

                    b.Property<int>("Neutralizes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("neutralizes");

                    b.Property<int>("PassengerAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("passengerassists");

                    b.Property<byte>("PermBan")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permban");

                    b.Property<byte>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.Property<int>("Repairs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("repairs");

                    b.Property<int>("Revives")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revives");

                    b.Property<int>("RndScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rndscore");

                    b.Property<int>("Rounds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rounds");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<int>("SkillScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skillscore");

                    b.Property<int>("SqlTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sqltime");

                    b.Property<int>("SqmTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sqmtime");

                    b.Property<int>("Suicides")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suicides");

                    b.Property<int>("TargetAssists")
                        .HasColumnType("INTEGER")
                        .HasColumnName("targetassists");

                    b.Property<int>("TeamDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamdamage");

                    b.Property<int>("TeamKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamkills");

                    b.Property<int>("TeamScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamscore");

                    b.Property<int>("TeamVehicleDamage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("teamvehicledamage");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time");

                    b.Property<byte>("UsedUnlocks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usedunlocks");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.ToTable("player");
                });

            modelBuilder.Entity("BF2Statistics.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("ip");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified))
                        .HasColumnName("lastupdate");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("port");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("prefix");

                    b.Property<int>("QueryPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("queryport");

                    b.Property<string>("RconPassword")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("rcon_password");

                    b.Property<int>("RconPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4711)
                        .HasColumnName("rcon_port");

                    b.HasKey("Id");

                    b.HasIndex("Ip", "Port")
                        .IsUnique();

                    b.ToTable("servers");
                });

            modelBuilder.Entity("BF2Statistics.Models.Unlock", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("UnlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kit");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("state");

                    b.HasKey("PlayerId", "UnlockId");

                    b.ToTable("unlocks");
                });

            modelBuilder.Entity("BF2Statistics.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("deaths");

                    b.Property<int>("Deaths0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths0");

                    b.Property<int>("Deaths1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths1");

                    b.Property<int>("Deaths2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths2");

                    b.Property<int>("Deaths3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths3");

                    b.Property<int>("Deaths4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths4");

                    b.Property<int>("Deaths5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths5");

                    b.Property<int>("Deaths6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths6");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("kills");

                    b.Property<int>("Kills0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills0");

                    b.Property<int>("Kills1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills1");

                    b.Property<int>("Kills2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills2");

                    b.Property<int>("Kills3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills3");

                    b.Property<int>("Kills4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills4");

                    b.Property<int>("Kills5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills5");

                    b.Property<int>("Kills6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills6");

                    b.Property<int>("RK0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk0");

                    b.Property<int>("RK1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk1");

                    b.Property<int>("RK2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk2");

                    b.Property<int>("RK3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk3");

                    b.Property<int>("RK4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk4");

                    b.Property<int>("RK5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk5");

                    b.Property<int>("RK6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rk6");

                    b.Property<int>("RoadKills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("roadkills");

                    b.Property<int>("Roadkills0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills0");

                    b.Property<int>("Roadkills1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills1");

                    b.Property<int>("Roadkills2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills2");

                    b.Property<int>("Roadkills3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills3");

                    b.Property<int>("Roadkills4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills4");

                    b.Property<int>("Roadkills5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills5");

                    b.Property<int>("Roadkills6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("roadkills6");

                    b.Property<int>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("time");

                    b.Property<int>("Time0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time0");

                    b.Property<int>("Time1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time1");

                    b.Property<int>("Time2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time2");

                    b.Property<int>("Time3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time3");

                    b.Property<int>("Time4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time4");

                    b.Property<int>("Time5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time5");

                    b.Property<int>("Time6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time6");

                    b.Property<int>("TimePara")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timepara");

                    b.HasKey("Id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("BF2Statistics.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AtmineDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atminedeaths");

                    b.Property<int>("AtmineFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atminefired");

                    b.Property<int>("AtmineHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atminehit");

                    b.Property<int>("AtmineKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atminekills");

                    b.Property<int>("AtmineTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atminetime");

                    b.Property<int>("C4Deaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("c4deaths");

                    b.Property<int>("C4Fired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("c4fired");

                    b.Property<int>("C4Hit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("c4hit");

                    b.Property<int>("C4Kills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("c4kills");

                    b.Property<int>("C4Time")
                        .HasColumnType("INTEGER")
                        .HasColumnName("c4time");

                    b.Property<int>("ClaymoreDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claymoredeaths");

                    b.Property<int>("ClaymoreFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claymorefired");

                    b.Property<int>("ClaymoreHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claymorehit");

                    b.Property<int>("ClaymoreKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claymorekills");

                    b.Property<int>("ClaymoreTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("claymoretime");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths0");

                    b.Property<int>("Deaths1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths1");

                    b.Property<int>("Deaths2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths2");

                    b.Property<int>("Deaths3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths3");

                    b.Property<int>("Deaths4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths4");

                    b.Property<int>("Deaths5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths5");

                    b.Property<int>("Deaths6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths6");

                    b.Property<int>("Deaths7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths7");

                    b.Property<int>("Deaths8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deaths8");

                    b.Property<int>("Fired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Fired0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired0");

                    b.Property<int>("Fired1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired1");

                    b.Property<int>("Fired2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired2");

                    b.Property<int>("Fired3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired3");

                    b.Property<int>("Fired4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired4");

                    b.Property<int>("Fired5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired5");

                    b.Property<int>("Fired6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired6");

                    b.Property<int>("Fired7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired7");

                    b.Property<int>("Fired8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fired8");

                    b.Property<int>("GrapplinghookDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghookdeaths");

                    b.Property<int>("GrapplinghookDeployed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghookdeployed");

                    b.Property<int>("GrapplinghookFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghookfired");

                    b.Property<int>("GrapplinghookHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghookhit");

                    b.Property<int>("GrapplinghookKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghookkills");

                    b.Property<int>("GrapplinghookTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("grapplinghooktime");

                    b.Property<int>("HandGrenadeDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handgrenadedeaths");

                    b.Property<int>("HandGrenadeFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handgrenadefired");

                    b.Property<int>("HandGrenadeHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handgrenadehit");

                    b.Property<int>("HandGrenadeKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handgrenadekills");

                    b.Property<int>("HandGrenadeTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("handgrenadetime");

                    b.Property<int>("Hit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Hit0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit0");

                    b.Property<int>("Hit1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit1");

                    b.Property<int>("Hit2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit2");

                    b.Property<int>("Hit3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit3");

                    b.Property<int>("Hit4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit4");

                    b.Property<int>("Hit5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit5");

                    b.Property<int>("Hit6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit6");

                    b.Property<int>("Hit7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit7");

                    b.Property<int>("Hit8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hit8");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills0");

                    b.Property<int>("Kills1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills1");

                    b.Property<int>("Kills2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills2");

                    b.Property<int>("Kills3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills3");

                    b.Property<int>("Kills4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills4");

                    b.Property<int>("Kills5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills5");

                    b.Property<int>("Kills6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills6");

                    b.Property<int>("Kills7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills7");

                    b.Property<int>("Kills8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kills8");

                    b.Property<int>("KnifeDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knifedeaths");

                    b.Property<int>("KnifeFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knifefired");

                    b.Property<int>("KnifeHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knifehit");

                    b.Property<int>("KnifeKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knifekills");

                    b.Property<int>("KnifeTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("knifetime");

                    b.Property<int>("ShockpadDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shockpaddeaths");

                    b.Property<int>("ShockpadFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shockpadfired");

                    b.Property<int>("ShockpadHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shockpadhit");

                    b.Property<int>("ShockpadKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shockpadkills");

                    b.Property<int>("ShockpadTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shockpadtime");

                    b.Property<int>("TacticalDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticaldeaths");

                    b.Property<int>("TacticalDeployed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticaldeployed");

                    b.Property<int>("TacticalFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticalfired");

                    b.Property<int>("TacticalHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticalhit");

                    b.Property<int>("TacticalKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticalkills");

                    b.Property<int>("TacticalTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tacticaltime");

                    b.Property<int>("Time0")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time0");

                    b.Property<int>("Time1")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time1");

                    b.Property<int>("Time2")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time2");

                    b.Property<int>("Time3")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time3");

                    b.Property<int>("Time4")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time4");

                    b.Property<int>("Time5")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time5");

                    b.Property<int>("Time6")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time6");

                    b.Property<int>("Time7")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time7");

                    b.Property<int>("Time8")
                        .HasColumnType("INTEGER")
                        .HasColumnName("time8");

                    b.Property<int>("ZiplineDeaths")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinedeaths");

                    b.Property<int>("ZiplineDeployed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinedeployed");

                    b.Property<int>("ZiplineFired")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinefired");

                    b.Property<int>("ZiplineHit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinehit");

                    b.Property<int>("ZiplineKills")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinekills");

                    b.Property<int>("ZiplineTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ziplinetime");

                    b.HasKey("Id");

                    b.ToTable("weapons");
                });

            modelBuilder.Entity("BF2Statistics.Models.Unlock", b =>
                {
                    b.HasOne("BF2Statistics.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
